config/routes.rb
Rails.application.routes.draw do
  resources :weather_infos
  resources :sensors

  root 'welcome#index'

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
end

app/models/weather_info.rb
class WeatherInfo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:latitude, :longitude)
    end
end

app/controllers/weather_infos_controller.rb
class WeatherInfosController < ApplicationController
  before_action :set_weather_info, only: [:show, :edit, :update, :destroy]

  # GET /weather_infos
  # GET /weather_infos.json
  def index
    @weather_infos = WeatherInfo.all
  end

  # GET /weather_infos/1
  # GET /weather_infos/1.json
  def show
  end

  # GET /weather_infos/new
  def new
    @weather_info = WeatherInfo.new
  end

  # GET /weather_infos/1/edit
  def edit
  end

  # POST /weather_infos
  # POST /weather_infos.json
  def create
    @weather_info = WeatherInfo.new(weather_info_params)

    respond_to do |format|
      if @weather_info.save
        format.html { redirect_to @weather_info, notice: 'Weather info was successfully created.' }
        format.json { render :show, status: :created, location: @weather_info }
      else
        format.html { render :new }
        format.json { render json: @weather_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weather_infos/1
  # PATCH/PUT /weather_infos/1.json
  def update
    respond_to do |format|
      if @weather_info.update(weather_info_params)
        format.html { redirect_to @weather_info, notice: 'Weather info was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather_info }
      else
        format.html { render :edit }
        format.json { render json: @weather_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weather_infos/1
  # DELETE /weather_infos/1.json
  def destroy
    @weather_info.destroy
    respond_to do |format|
      format.html { redirect_to weather_infos_url, notice: 'Weather info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather_info
      @weather_info = WeatherInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_info_params
      params.require(:weather_info).permit(:temperature, :humidity, :generated_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/helpers/weather_infos_helper.rb
module WeatherInfosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlertaSismicaTemprana</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sensors</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.latitude %></td>
        <td><%= sensor.longitude %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @sensor.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sensor.longitude %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>

app/views/weather_infos/_form.html.erb
<%= form_for(@weather_info) do |f| %>
  <% if @weather_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weather_info.errors.count, "error") %> prohibited this weather_info from being saved:</h2>

      <ul>
      <% @weather_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :humidity %><br>
    <%= f.text_field :humidity %>
  </div>
  <div class="field">
    <%= f.label :generated_at %><br>
    <%= f.text_field :generated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weather_infos/edit.html.erb
<h1>Editing Weather Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather_info %> |
<%= link_to 'Back', weather_infos_path %>

app/views/weather_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weather Infos</h1>

<table>
  <thead>
    <tr>
      <th>Temperature</th>
      <th>Humidity</th>
      <th>Generated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weather_infos.each do |weather_info| %>
      <tr>
        <td><%= weather_info.temperature %></td>
        <td><%= weather_info.humidity %></td>
        <td><%= weather_info.generated_at %></td>
        <td><%= link_to 'Show', weather_info %></td>
        <td><%= link_to 'Edit', edit_weather_info_path(weather_info) %></td>
        <td><%= link_to 'Destroy', weather_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather info', new_weather_info_path %>

app/views/weather_infos/new.html.erb
<h1>New Weather Info</h1>

<%= render 'form' %>

<%= link_to 'Back', weather_infos_path %>

app/views/weather_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temperature:</strong>
  <%= @weather_info.temperature %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @weather_info.humidity %>
</p>

<p>
  <strong>Generated at:</strong>
  <%= @weather_info.generated_at %>
</p>

<%= link_to 'Edit', edit_weather_info_path(@weather_info) %> |
<%= link_to 'Back', weather_infos_path %>